package com.project1;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class ReimbursmentServlet extends HttpServlet {
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		response.setContentType("text/html");
		PrintWriter out = response.getWriter();
		
		out.print("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>Document</title>\r\n"
				+ "    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n"
				+ "        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\r\n"
				+ "    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n"
				+ "        integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n"
				+ "        crossorigin=\"anonymous\"></script>\r\n"
				+ "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\"\r\n"
				+ "        integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\"\r\n"
				+ "        crossorigin=\"anonymous\"></script>\r\n"
				+ "\r\n"
				+ "    <style>\r\n"
				+ "        .container {\r\n"
				+ "            width: 50%;\r\n"
				+ "            padding: 40px;\r\n"
				+ "            border-radius: 30px;\r\n"
				+ "            background: #191919;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .container label {\r\n"
				+ "            color: grey;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .container input,\r\n"
				+ "        .container textarea,\r\n"
				+ "        .container select {\r\n"
				+ "            border: 2px solid #3498db;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .container button {\r\n"
				+ "            border: 0;\r\n"
				+ "            background: none;\r\n"
				+ "            display: block;\r\n"
				+ "            text-align: center;\r\n"
				+ "            border: 2px solid #c9c613;\r\n"
				+ "            outline: none;\r\n"
				+ "            color: white;\r\n"
				+ "            border-radius: 24px;\r\n"
				+ "            transition: 0.25s;\r\n"
				+ "            cursor: pointer\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .container button:hover {\r\n"
				+ "            background: #3498db\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            margin: 0;\r\n"
				+ "            padding: 0;\r\n"
				+ "            font-family: sans-serif;\r\n"
				+ "            background: linear-gradient(to right, #81802b, #23538a)\r\n"
				+ "                /* background-image: url('https://images.pond5.com/subtle-gradient-moving-shapes-background-footage-089496665_prevstill.jpeg'); */\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .jumbotron {\r\n"
				+ "            background: linear-gradient(to right, #81802b, #23538a)\r\n"
				+ "                /* background-image: url('https://images.pond5.com/subtle-gradient-moving-shapes-background-footage-089496665_prevstill.jpeg'); */\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .jumbotron p {\r\n"
				+ "            color: black;\r\n"
				+ "            font-weight: 500\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .jumbotron h1 {\r\n"
				+ "            color: black;\r\n"
				+ "            font-weight: 500\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        nav {\r\n"
				+ "            background-color: #191919;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .navbar a {\r\n"
				+ "            color: #c9c613;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "    <!-- navbar -->\r\n"
				+ "    <nav class=\"navbar fixed-top navbar-expand-lg navbar-light\">\r\n"
				+ "        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n"
				+ "            <ul class=\"navbar-nav mr-auto\">\r\n"
				+ "                <li class=\"nav-item dropdown\">\r\n"
				+ "                    <a class=\"nav-link dropdown-toggle text-warning\" href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n"
				+ "                        data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n"
				+ "                        Actions\r\n"
				+ "                    </a>\r\n"
				+ "                    <div class=\"dropdown-menu bg-dark\" aria-labelledby=\"navbarDropdown\">\r\n"
				+ "                        <a class=\"dropdown-item text-warning bg-dark\" href=\"/ticketTable.html\">Pending Tickets</a>\r\n"
				+ "                        <a class=\"dropdown-item text-warning bg-dark\" href=\"\">Ticket History</a>\r\n"
				+ "                </li>\r\n"
				+ "                <li class=\"nav-item\">\r\n"
				+ "                    <a class=\"nav-link text-warning\" href=\"/reimbursement.html\">Form</a>\r\n"
				+ "                </li>\r\n"
				+ "            </ul>\r\n"
				+ "            <form class=\"form-inline my-2 my-lg-0\" action=\"index.html\">\r\n"
				+ "                <button class=\"btn btn-outline-warning my-2 my-sm-0\" type=\"submit\">Logout</button>\r\n"
				+ "            </form>\r\n"
				+ "        </div>\r\n"
				+ "    </nav>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!-- header -->\r\n"
				+ "    <div class=\"jumbotron\">\r\n"
				+ "        <h1 class=\"display-6\">Reimbursement Requests</h1>\r\n"
				+ "        <p class=\"lead\">In the form below select what your reimbursement request is for as\r\n"
				+ "            well as provide the\r\n"
				+ "            reimbursement amount with a short description</p>\r\n"
				+ "        <hr color=\"#000\">\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!-- main-content -->\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <h3 class=\"text-center text-light\">Reimbursement Form</h3>\r\n"
				+ "        <hr color=\"81802b\">\r\n"
				+ "        <form onsubmit=\"event.preventDefault()\">\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"reimbursementType\">Select Reimbursement</label>\r\n"
				+ "                <select class=\"form-control bg-dark text-light\" id=\"exampleFormControlSelect1\">\r\n"
				+ "                    <option disabled hidden selected>--Select One--</option>\r\n"
				+ "                    <option class=\"text-light\">LODGING</option>\r\n"
				+ "                    <option class=\"text-light\">TRAVEL</option>\r\n"
				+ "                    <option class=\"text-light\">FOOD</option>\r\n"
				+ "                    <option class=\"text-light\">OTHER</option>\r\n"
				+ "                </select>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"exampleFormControlInput1\">Enter Reimbursement Amount</label>\r\n"
				+ "                <input type=\"number\" min=\"5\" step=\"0.01\" class=\"form-control bg-dark text-light\" placeholder=\"$0.00\">\r\n"
				+ "            </div>\r\n"
				+ "\r\n"
				+ "            <div class=\"form-group\">\r\n"
				+ "                <label for=\"exampleFormControlTextarea1\">Please provide a short description of your expenses</label>\r\n"
				+ "                <textarea class=\"form-control bg-dark text-light\" id=\"exampleFormControlTextarea1\" rows=\"3\"\r\n"
				+ "                    placeholder=\"Example: I spent $57 for hotel lodging\"></textarea>\r\n"
				+ "            </div>\r\n"
				+ "            <button type=\"submit\" class=\"btn btn-outline-dark text-light\">Submit</button>\r\n"
				+ "        </form>\r\n"
				+ "        <br>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!-- footer -->\r\n"
				+ "    <!-- <div class=\"jumbotron jumbotron-fluid\">\r\n"
				+ "        <div class=\"container\">\r\n"
				+ "            <h1 class=\"display-4\">Fluid jumbotron</h1>\r\n"
				+ "            <p class=\"lead\">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>\r\n"
				+ "        </div>\r\n"
				+ "    </div> -->\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>");
		
	}

}
